pull_request_rules:
  - name: Merge approved pull requests when checks pass
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=all
    actions:
      merge:
        method: squash
